### ISSUE TITLE
Number of lines in spec files are too long

### ISSUE THREAD

**Issue by makinwab** [andela-cnwosu/kuruka#6]
In some of your spec files, you have over 150 lines of code. You can reduce this by having separate files for different specs.

For instance in your [bookings controller spec](https://github.com/andela-cnwosu/kuruka/blob/master/spec/controllers/bookings_controller_spec.rb),  you can have a `bookings` directory with files `create_booking_spec.rb` , `delete_user_spec.rb`, `update_booking_spec.rb`, etc. inside the `controllers` directory.

Please fix all instances of this issue.

**Comment by makinwab** [comment]
Has this been fixed @andela-cnwosu ? If it has, please close and comment.

**Comment by chinezenwosu** [comment]
Yes, this has been fixed @andela-bmakinwa.
